#pragma once

#include "NativeGameplayTags.h"

namespace SSGameplayTags
{
	/**** Input Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Esc)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_RMB)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LMB)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Acceleration)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Alt)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Jump)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Interaction)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot1)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot2)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot3)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot4)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot5)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot6)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot7)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot8)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot9)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Slot0)

	/**** Message Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Message)
	
	/**** Attributes Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Primary)
	
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Health)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxHealth)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_Mana)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxMana)
	
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MovementSpeed)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Attribute_Main_MaxMovementSpeed)

	/**** Event Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_SpawnEffect)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_StartWeaponHit)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Montage_StopWeaponHit)

	/**** Effect Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_HitReact)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_DamageImmunity)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Effect_Immortality)

	/**** Menu Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Menu_SaveSlot)

	/**** Ability cooldown Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cooldown_Weapon)
	
	/**** Ability cost Tags ****/
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost_Mana)
	SIMPLESETUP_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Cost_Health)
}
